name: Node.js CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golvue
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install packages
        run: npm install
      - name: Set Creds
        run: git config user.name "mhenrique94" && git config user.email "mhenrique94@outlook.com"
      - name: Deploy
        run: npm run deploy
